name: rapid
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - notebook
  - tqdm
  - scikit-learn
  - matplotlib
  - seaborn